### ISSUE TITLE
How to access directly some deeply nested elements?

### ISSUE THREAD

**Issue by boumboum** [tamerh/xml-stream-parser#5]
This is rather a question as an issue
given your example but a bit extended
```
<?xml version="1.0" encoding="UTF-8"?>
<lectures>
   <libraries>
       <library name="xx">
          <book>
          ...
          </book>
          ...
       </library>
       <library name="yy">
         <book>
         ...
         </book>
         ...
       </library>
   </libraries>
   <bookstores>
      <bookstore name="xx">
         <book>
         ...
         </book>
         ...
      </bookstore>
      <bookstore name="yy">
         <book>
         ...
         </book>
         ..
      </bookstore>
   </bookstores>
</lectures>
```

How get to access directly to all books in bookstores (but not those in libraries) in an efficient manner?
Because this doesn't work:
`parser:= NewXMLParser(br, "lectures/bookstores/bookstore/book")`

And what is your recommendation for parsing large (>1gb) XML files with loads of elements without reparsing the file again and again?

**Comment by tamerh** [comment]
Hi 

yes path based parsing does not work since it could affect the performance and complicate things 
so i didn't prefer. My recommendation for large files and reading it once would be to parse with streaming way like this library considering standart library is not efficient at the moment.

I assume there are many books under each `bookstore` and not efficient stream over `bookstore` and get child books right?

One solution would be skipping `libraries` element which does not work at the moment. for example

`parser:= NewXMLParser(br, "book").SkipElements([]string{"libraries"})
`

At the moment skip only works under the stream element but not outside. I will think and add this feature and let you know.

**Comment by boumboum** [comment]
OK. I'm waiting for your update.
Actually in my case I have 2 main blocks: MasterData and OrderData
Under each main blocks I have tons of elements (corresponding to different database tables).
The best would be to be able to load all those master data tables (elements) concurrently to the database. 
So, because you are already using goroutines for parsing this would be feasible, but somehow I have to specify the path to the required element.
Once all master data are loaded to the DB I have to read all elements (which are also complicated (deeply nested) structures) under OrderData. This reading is sequential, so your reading method works fine for this.
I could also use for my case SkipElements for reading the MasterData but in this case each time I have to list every other elements I do not want to parse and after change this list for the subsequent parsing. And this is obviously not very handy.

**Comment by tamerh** [comment]
Ok i got your usecases. Although it is good that at least it could work with unhandy way. It would have been probably inefficient as well so worth to add this feature.

Now i have made commit to master for this. In order to not effect existing performance and behaviour since i am also heavy user and in the middle of a project :)  so this feature will be activated separately like so, base on initial example.

`parser:= NewXMLParser(br, "book").SkipElements([]string{"libraries"}).SkipOuterElements()  `

I have checked with benchmark and it seems looks fine to me. Have look with your data and let me know and i will tag as a new version.

**Comment by tamerh** [comment]
@boumboum closing this ticket as i said feature now in master. Just also let you know that with idea and initial implementation via PR, in next months library will support xpath queries for parsed xmlelement.
